const MB_APPLMODAL           = 0
const MB_COMPOSITE           = 2         '  use composite chars
const MB_DEFAULT_DESKTOP_ONLY= 131072
const MB_DEFBUTTON1          = 0
const MB_DEFBUTTON2          = 256
const MB_DEFBUTTON3          = 512
const MB_DEFMASK             = 3840
const MB_ABORTRETRYIGNORE    = 2
const MB_ICONASTERISK        = 64
const MB_ICONEXCLAMATION     = 48
const MB_ICONHAND            = 16
const MB_ICONINFORMATION     = MB_ICONASTERISK
const MB_ICONMASK            = 240
const MB_ICONQUESTION        = 32
const MB_ICONSTOP            = MB_ICONHAND
const MB_MISCMASK            = 49152
const MB_MODEMASK            = 12288
const MB_NOFOCUS             = 32768
const MB_OK                  = 0
const MB_OKCANCEL            = 1
const MB_PRECOMPOSED         = 1         '  use precomposed chars
const MB_RETRYCANCEL         = 5
const MB_SETFOREGROUND       = 65536
const MB_SYSTEMMODAL         = 4096
const MB_TASKMODAL           = 8192
const MB_TOPMOST             = 262114
const MB_TYPEMASK            = 15
const MB_USEGLYPHCHARS       = 4         '  use glyph chars, not ctrl chars
const MB_YESNO               = 4
const MB_YESNOCANCEL         = 3

const IDABORT = 3
const IDIGNORE = 5
const IDNO = 7
const IDOK = 1
const IDRETRY = 4
const IDYES = 6


